# Live
# :api_key: "fdfrH1pmKQO5dtFW66wz5crjEdzGEpov"
# :public_key: "pk_mu7HmfCu2KT0o5Yo4XDGVSelP0xVN"
---
# Test
:api_key: "g8JtdkufTNXPZ983tPQErM2NoicYUyp4"
:public_key: "pk_RP3bFbsOCxaJXBaNeVlN9badskKOW"

